### ISSUE TITLE
bcm94360cd 蓝牙无法打开。隔空投送等功能无法使用

### ISSUE THREAD

**Issue by HatcherX** [hackintosh-efi/MAXSUN-B660M-TERMINATOR-OpenCore#1]
bcm94360cd 蓝牙无法打开。隔空投送等功能无法使用，请大佬帮忙看下是什么原因
<img width="755" alt="image" src="https://user-images.githubusercontent.com/29924661/233767625-f9ef8267-afbe-4e5f-a6bc-d7ebdac30547.png">

**Comment by WuLongMiTaoLaiYiDa** [comment]
每个人的电脑因机箱不同所以USB接口都会不同，上传的EFI配置文件中的USB定制文件一般只能保证你完成安装
建议使用[usbtoolbox](https://github.com/USBToolBox/tool)自行定制USB驱动
